version: '3'

services:
  veilid-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "/root/veilid/target/debug/veilid-server" 
    volumes:
      - /tmp/veilid-sever:/root/.local/share/veilid
